language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t robesantororobesantoro/docker_rest -f Dockerfile .

script:
  - docker run robesantororobesantoro/docker_rest ./mvnw test

after_success:
  - docker build -t robesantororobesantoro/docker_rest -f Dockerfile_prod .

  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push robesantororobesantoro/docker_rest

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'test_docker_rest'
  env: 'Testdockerrest-env'
  bucket_name: 'elasticbeanstalk-us-east-2-801320686542'
  bucket_path: 'docker-rest'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  