FROM maven:3.8.2-jdk-11-slim as build_test
LABEL maintainer="robesantoro@gmail.com"
WORKDIR /usr/app
ADD src ./src
ADD .mvn/ ./.mvn
ADD pom.xml ./
ADD mvnw ./
RUN ["mvn","package"]

FROM busybox
WORKDIR /usr
COPY --from=build_test /usr/app/ /usr/app
CMD ["sh"]
